---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Jakob Voß"
title: "Versuch einer Bibliographie von Bibliographien von Bibliographien von Bibliographien"
urn:
date: 
comments: false
sharing: true
footer: true
...
